language: node_js
node_js:
  - 0.8
  - 0.10
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq socat
  - ssh-keygen -t rsa -f ~/.ssh/id_rsa -N ''
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - ssh-keyscan -t rsa localhost >> ~/.ssh/known_hosts
  - which node
script: npm run travis-test
