sudo: false
language: node_js
node_js:
  - 0.12
  - 4
  - 6
env:
  - PYVER=2
  - PYVER=3
addons:
  apt:
    packages:
      - socat
      - python3
before_install:
  - ssh-keygen -t rsa -f ~/.ssh/id_rsa -N ''
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - ssh-keyscan -t rsa localhost >> ~/.ssh/known_hosts
  - echo . ~/.nvm/nvm.sh > ~/.bashrc.new
  - cat ~/.bashrc >> ~/.bashrc.new
  - mv ~/.bashrc.new ~/.bashrc
  - nvm alias default "$(nvm current)"
  - ssh localhost node --version
  - echo "$PATH"
  - mkdir -p "$HOME/.local/bin"
  - ln -s "$(which python$PYVER)" "$HOME/.local/bin/python"
  - ssh localhost python --version
script: npm run travis-test
