sudo: required
dist: trusty
language: node_js
node_js:
  - 4
  - 6
  - 8
env:
  - PYENV_VERSION=2.7
  - PYENV_VERSION=3.6
addons:
  apt:
    packages:
      - socat
      - python3
before_install:
  - ssh-keygen -t rsa -f ~/.ssh/id_rsa -N ''
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - ssh-keyscan -t rsa localhost >> ~/.ssh/known_hosts
  - echo . ~/.nvm/nvm.sh > ~/.bashrc.new
  - cat ~/.bashrc >> ~/.bashrc.new
  - mv ~/.bashrc.new ~/.bashrc
  - nvm alias default "$(nvm current)"
  - ssh localhost node --version
  - ssh localhost python --version
script:
  - npm run travis-test
