sudo: required
dist: trusty
language: node_js
node_js:
  - 4
  - 6
  - 8
env:
  - PYVER=2
  - PYVER=3
addons:
  apt:
    packages:
      - socat
      - python3
before_install:
  - ssh-keygen -t rsa -f ~/.ssh/id_rsa -N ''
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - ssh-keyscan -t rsa localhost >> ~/.ssh/known_hosts
  - echo . ~/.nvm/nvm.sh > ~/.bashrc.new
  - echo 'PATH=$HOME/.local/bin:$PATH' >> ~/.bashrc.new
  - cat ~/.bashrc >> ~/.bashrc.new
  - mv ~/.bashrc.new ~/.bashrc
  - cat ~/.bashrc
  - nvm alias default "$(nvm current)"
  - ssh localhost node --version
  - ssh localhost python --version
  - cat "$(which python$PYVER)"
  - mkdir -p "$HOME/.local/bin"
  - ln -s "$(which python$PYVER)" "$HOME/.local/bin/python"
  - ls -l "$HOME/.local/bin"
  - ssh localhost python --version
script: npm run travis-test
